// <auto-generated />
using System;
using CourierManagement.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourierManagement.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190318170003_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourierManagement.Core.Models.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ComplainedDeliveryId");

                    b.Property<DateTime>("ComplaintDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<int>("Status");

                    b.Property<DateTime>("SubmissionDate");

                    b.HasKey("Id");

                    b.HasIndex("ComplainedDeliveryId");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("CourierManagement.Core.Models.Courier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<DateTime>("Birthdate");

                    b.Property<string>("City");

                    b.Property<string>("Company");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FirstName");

                    b.Property<int>("Gender");

                    b.Property<string>("LastName");

                    b.Property<string>("Pesel")
                        .IsRequired();

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("PostalCode");

                    b.HasKey("Id");

                    b.ToTable("Couriers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ul. Jasna 1",
                            Birthdate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Gliwice",
                            EmailAddress = "jan.kowalski@mail.com",
                            FirstName = "Jan",
                            Gender = 1,
                            LastName = "Kowalski",
                            Pesel = "00000000001",
                            PhoneNumber = "123-456-789",
                            PostalCode = "44-100"
                        },
                        new
                        {
                            Id = 2,
                            Address = "ul. Ciemna 2",
                            Birthdate = new DateTime(1980, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Knurów",
                            EmailAddress = "janina.kowalska@mail.com",
                            FirstName = "Janina",
                            Gender = 2,
                            LastName = "Kowalska",
                            Pesel = "000000000002",
                            PhoneNumber = "789-456-123",
                            PostalCode = "44-193"
                        });
                });

            modelBuilder.Entity("CourierManagement.Core.Models.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AcceptanceDate");

                    b.Property<decimal>("Cost");

                    b.Property<int>("DeliveryCourierId");

                    b.Property<int>("Height");

                    b.Property<decimal>("InsuranceCost");

                    b.Property<bool>("IsFragile");

                    b.Property<bool>("IsInsured");

                    b.Property<bool>("IsReceived");

                    b.Property<bool>("IsSent");

                    b.Property<int>("Length");

                    b.Property<int>("PaymentType");

                    b.Property<DateTime>("ReceivedDate");

                    b.Property<int>("RecipientId");

                    b.Property<int>("SenderId");

                    b.Property<DateTime>("SentDate");

                    b.Property<int>("Weight");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryCourierId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("Deliveries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptanceDate = new DateTime(2019, 3, 18, 18, 0, 2, 617, DateTimeKind.Local).AddTicks(7256),
                            Cost = 100m,
                            DeliveryCourierId = 1,
                            Height = 300,
                            InsuranceCost = 0m,
                            IsFragile = false,
                            IsInsured = false,
                            IsReceived = false,
                            IsSent = false,
                            Length = 200,
                            PaymentType = 0,
                            ReceivedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecipientId = 1,
                            SenderId = 1,
                            SentDate = new DateTime(2019, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 2000,
                            Width = 250
                        },
                        new
                        {
                            Id = 2,
                            AcceptanceDate = new DateTime(2019, 3, 18, 18, 0, 2, 624, DateTimeKind.Local).AddTicks(2201),
                            Cost = 50m,
                            DeliveryCourierId = 2,
                            Height = 200,
                            InsuranceCost = 0m,
                            IsFragile = true,
                            IsInsured = false,
                            IsReceived = false,
                            IsSent = false,
                            Length = 1000,
                            PaymentType = 1,
                            ReceivedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecipientId = 2,
                            SenderId = 2,
                            SentDate = new DateTime(2019, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 10000,
                            Width = 200
                        });
                });

            modelBuilder.Entity("CourierManagement.Core.Models.Recipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Company");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FirstName");

                    b.Property<int>("Gender");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("PostalCode");

                    b.HasKey("Id");

                    b.ToTable("Recipients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ul. Odbiorcza 1",
                            City = "Gliwice",
                            Company = "Firma Krzak",
                            EmailAddress = "pan.odbiorca@mail.com",
                            FirstName = "Pan",
                            Gender = 1,
                            LastName = "Odbiorca",
                            PhoneNumber = "135-246-357",
                            PostalCode = "44-100"
                        },
                        new
                        {
                            Id = 2,
                            Address = "ul. Odbiorcza 2",
                            City = "Gliwice",
                            Company = "Firma Kogucik",
                            EmailAddress = "pani.odbiorczyni@mail.com",
                            FirstName = "Pani",
                            Gender = 2,
                            LastName = "Odbiorczyni",
                            PhoneNumber = "246-357-468",
                            PostalCode = "44-100"
                        });
                });

            modelBuilder.Entity("CourierManagement.Core.Models.Return", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AcceptanceDate");

                    b.Property<decimal>("Cost");

                    b.Property<int>("DeliveryId");

                    b.Property<bool>("IsReturned");

                    b.Property<DateTime>("ReturnDate");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.ToTable("Returns");
                });

            modelBuilder.Entity("CourierManagement.Core.Models.Sender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Company");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FirstName");

                    b.Property<int>("Gender");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("PostalCode");

                    b.HasKey("Id");

                    b.ToTable("Senders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ul. Nadawcza 1",
                            City = "Gliwice",
                            Company = "Firma Krzak",
                            EmailAddress = "pan.nadawca@mail.com",
                            FirstName = "Pan",
                            Gender = 1,
                            LastName = "Nadawca",
                            PhoneNumber = "135-246-357",
                            PostalCode = "44-100"
                        },
                        new
                        {
                            Id = 2,
                            Address = "ul. Nadawcza 2",
                            City = "Gliwice",
                            Company = "Firma Kogucik",
                            EmailAddress = "pani.nadawczyni@mail.com",
                            FirstName = "Pani",
                            Gender = 2,
                            LastName = "Nadawczyni",
                            PhoneNumber = "246-357-468",
                            PostalCode = "44-100"
                        });
                });

            modelBuilder.Entity("CourierManagement.Core.Models.Complaint", b =>
                {
                    b.HasOne("CourierManagement.Core.Models.Delivery", "ComplainedDelivery")
                        .WithMany()
                        .HasForeignKey("ComplainedDeliveryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CourierManagement.Core.Models.Delivery", b =>
                {
                    b.HasOne("CourierManagement.Core.Models.Courier", "DeliveryCourier")
                        .WithMany()
                        .HasForeignKey("DeliveryCourierId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CourierManagement.Core.Models.Recipient", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CourierManagement.Core.Models.Sender", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CourierManagement.Core.Models.Return", b =>
                {
                    b.HasOne("CourierManagement.Core.Models.Delivery", "Delivery")
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
